import { jsPDF } from 'jspdf';
import { Patient, Consent, Device, MedicalOrder } from '../types';
import amavitaLogo from '../assets/amavita-logo.png?inline';
import { POWERED_BY, PRODUCT_NAME } from './branding';

/**
 * Utility to generate professional PDFs using jsPDF.
 */

interface PDFGeneratorMeta {
  documentId: string;
  generatedBy: string;
  dateTime: string;
}

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const CONTENT_BOTTOM = 276;

// ── Brand palette ───────────────────────────────────────────────────────────
const TEAL   = { r: 10,  g: 148, b: 155 }; // primary teal #0A949B
const NAVY   = { r: 15,  g: 45,  b: 90  }; // dark navy  #0F2D5A
const SLATE6 = { r: 71,  g: 85,  b: 105 }; // slate-600
const SLATE5 = { r: 100, g: 116, b: 139 }; // slate-500
const SLATE3 = { r: 203, g: 213, b: 225 }; // slate-300
const INK    = { r: 15,  g: 23,  b: 42  }; // slate-900

function setTeal(doc: jsPDF)  { doc.setTextColor(TEAL.r, TEAL.g, TEAL.b); }
function setNavy(doc: jsPDF)  { doc.setTextColor(NAVY.r, NAVY.g, NAVY.b); }
function setInk(doc: jsPDF)   { doc.setTextColor(INK.r,  INK.g,  INK.b);  }
function setSlate6(doc: jsPDF){ doc.setTextColor(SLATE6.r, SLATE6.g, SLATE6.b); }
function setSlate5(doc: jsPDF){ doc.setTextColor(SLATE5.r, SLATE5.g, SLATE5.b); }

function applyPdfMetadata(doc: jsPDF, documentTitle: string): void {
  doc.setProperties({
    title: `${PRODUCT_NAME} - ${documentTitle}`,
    subject: `${documentTitle} generated by ${PRODUCT_NAME}`,
    author: PRODUCT_NAME,
    creator: `${PRODUCT_NAME} | ${POWERED_BY}`
  });
}

function drawWrappedText(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight = 4): number {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + (lines.length * lineHeight);
}

function drawFitText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  minFontSize = 5.8
): void {
  let size = fontSize;
  doc.setFontSize(size);
  while (doc.getTextWidth(text) > maxWidth && size > minFontSize) {
    size -= 0.2;
    doc.setFontSize(size);
  }
  if (doc.getTextWidth(text) <= maxWidth) {
    doc.text(text, x, y);
    doc.setFontSize(fontSize);
    return;
  }

  const ellipsis = '...';
  let clipped = text;
  while (clipped.length > 0 && doc.getTextWidth(`${clipped}${ellipsis}`) > maxWidth) {
    clipped = clipped.slice(0, -1);
  }
  doc.text(`${clipped}${ellipsis}`, x, y);
  doc.setFontSize(fontSize);
}

/** Teal bullet used in consent terms */
function drawBullet(doc: jsPDF, text: string, x: number, y: number, maxWidth: number): number {
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.circle(x + 0.8, y - 1.1, 0.65, 'F');
  return drawWrappedText(doc, text, x + 3.4, y, maxWidth - 3.4, 3.6);
}

/** Section heading card: left teal accent bar + section number + label */
function drawSectionHeader(doc: jsPDF, label: string, y: number): void {
  // left teal bar
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.rect(12, y, 2, 5.6, 'F');
  // text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.2);
  setTeal(doc);
  doc.text(label.toUpperCase(), 16.5, y + 4.2);
}

/** Draws a key-value pair: label in slate-500, value in bold ink */
function drawKV(doc: jsPDF, label: string, value: string, lx: number, vx: number, y: number): void {
  doc.setFont('helvetica', 'normal'); setSlate5(doc); doc.setFontSize(8);
  doc.text(label, lx, y);
  doc.setFont('helvetica', 'bold'); setInk(doc); doc.setFontSize(8);
  doc.text(value, vx, y);
}

function drawStackedKV(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  maxWidth: number,
  valueFontSize = 7.1,
  minFontSize = 5.8
): void {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(5.7);
  setSlate5(doc);
  doc.text(label, x, y);
  doc.setFont('helvetica', 'bold');
  setInk(doc);
  drawFitText(doc, value, x, y + 3.8, maxWidth, valueFontSize, minFontSize);
}

/** Rounded badge pill */
function drawBadge(doc: jsPDF, label: string, x: number, y: number, bg: number[], fg: number[] = [255,255,255]): void {
  const w = doc.getStringUnitWidth(label) * 7.5 / doc.internal.scaleFactor + 4;
  doc.setFillColor(bg[0], bg[1], bg[2]);
  doc.roundedRect(x, y - 3.5, w, 5, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(fg[0], fg[1], fg[2]);
  doc.text(label, x + 2, y);
}

function drawHeader(doc: jsPDF, _title: string, patient: Patient, meta: PDFGeneratorMeta) {
  // ── Top white band ──────────────────────────────────────────────────────
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, PAGE_WIDTH, 24, 'F');

  // Decorative teal circle top-right, fully inside the 7-10 mm safe area.
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.circle(194, 11.5, 5.8, 'F');
  // ECG / heartbeat line inside the circle (simplified polyline)
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.55);
  doc.lines([[1.2,0],[0.8,-1.8],[0.8,3.4],[0.8,-2.7],[0.8,1.4],[1.2,0]], 190.2, 11.5, [1,1]);

  // AMAVITA logo
  try {
    doc.addImage(amavitaLogo, 'PNG', 12, 4.5, 52, 8, 'amavita-logo', 'FAST');
  } catch { /* silent */ }

  // Product name and powered-by line.
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  setNavy(doc);
  doc.text(PRODUCT_NAME, 13.5, 16.5);
  doc.setFontSize(5.4);
  setTeal(doc);
  doc.text(POWERED_BY, 13.5, 20.2);

  // Doc meta (right column)
  const metaX = 125;
  const labelW = 12;
  doc.setFontSize(6.4);

  setSlate6(doc); doc.setFont('helvetica', 'normal');
  doc.text('DOC ID:', metaX, 8.2);
  doc.text('DATE:',   metaX, 12.6);
  doc.text('BY:',     metaX, 17);

  setNavy(doc); doc.setFont('helvetica', 'bold');
  drawFitText(doc, meta.documentId, metaX + labelW, 8.2, 45, 6.4);
  drawFitText(doc, meta.dateTime, metaX + labelW, 12.6, 45, 6.4);
  drawFitText(doc, meta.generatedBy, metaX + labelW, 17, 45, 6.4);

  // Thin separator
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.setLineWidth(0.3);
  doc.line(0, 24, PAGE_WIDTH, 24);
}

function drawFooter(doc: jsPDF, meta: PDFGeneratorMeta, pageNum: number) {
  const fY = PAGE_HEIGHT - 13;

  // Navy band
  doc.setFillColor(NAVY.r, NAVY.g, NAVY.b);
  doc.rect(0, fY, PAGE_WIDTH, 13, 'F');

  // Teal accent stripe (left edge only)
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.rect(0, fY, 3, 13, 'F');

  // Main footer text (starts right after the stripe, no icon circle)
  doc.setFont('helvetica', 'bold'); doc.setFontSize(6.3); doc.setTextColor(255, 255, 255);
  doc.text(`${PRODUCT_NAME.toUpperCase()}  \u2022  ${POWERED_BY.toUpperCase()}  \u2022  CONFIDENTIAL MEDICAL RECORD  \u2022  HIPAA COMPLIANT`, 7, fY + 5.5);
  // Doc ID line — white
  doc.setFont('helvetica', 'normal'); doc.setFontSize(5.8); doc.setTextColor(255, 255, 255);
  doc.text(`Document Unique ID: ${meta.documentId}  \u2022  Page ${pageNum}`, 7, fY + 10.2);

  // Decorative ECG at right
  doc.setDrawColor(TEAL.r, TEAL.g, TEAL.b);
  doc.setLineWidth(0.65);
  doc.lines([[4,0],[1.5,-3],[1.5,6],[1.5,-4.5],[1.5,2.2],[4,0]], 177, fY + 7, [1,1]);
}

function drawAllFooters(doc: jsPDF, meta: PDFGeneratorMeta) {
  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    drawFooter(doc, meta, page);
  }
}

function ensureSectionSpace(
  doc: jsPDF,
  requiredHeight: number,
  currentY: number,
  title: string,
  patient: Patient,
  meta: PDFGeneratorMeta
): number {
  if (currentY + requiredHeight <= CONTENT_BOTTOM) return currentY;
  doc.addPage();
  drawHeader(doc, title, patient, meta);
  return 36;
}

export function generateConsentPDF(patient: Patient, consent: Consent, meta: PDFGeneratorMeta): string {
  const doc = new jsPDF();
  const documentTitle = 'Patient Care & Consent Agreement';
  applyPdfMetadata(doc, documentTitle);

  drawHeader(doc, documentTitle, patient, meta);

  // ── Document title ────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  setNavy(doc);
  doc.text('PATIENT CARE & CONSENT AGREEMENT', 12, 32);
  // Teal underline
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.rect(12, 34.8, 30, 0.9, 'F');

  // ── SECTION 1: PATIENT DEMOGRAPHICS ──────────────────────────────────────
  drawSectionHeader(doc, '1. Patient Demographics', 38);

  // Demographics card
  const d1Y = 45;
  const dH  = 26;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.setLineWidth(0.35);
  doc.roundedRect(12, d1Y, 186, dH, 1.6, 1.6, 'FD');

  // Vertical divider
  doc.setLineWidth(0.3);
  doc.line(73, d1Y + 3, 73, d1Y + dH - 3);

  const leftX = 15;
  const rightX = 77;
  const row1 = d1Y + 5.2, row2 = d1Y + 13, row3 = d1Y + 20.8;

  drawStackedKV(doc, 'Name', `${patient.firstName} ${patient.lastName}`, leftX, row1, 53, 7);
  drawStackedKV(doc, 'DOB', patient.birthDate, leftX, row2, 53, 7);
  drawStackedKV(doc, 'Medicare ID', patient.medicareId || 'N/A', leftX, row3, 53, 7);

  drawStackedKV(doc, 'Nursing Home', patient.nursingHome, rightX, row1, 116, 6.9, 5.2);
  drawStackedKV(doc, 'Room', patient.room || 'N/A', rightX, row2, 116, 7);
  drawStackedKV(doc, 'Program', patient.assignedProgram, rightX, row3, 116, 7);

  // ── SECTION 2: CONSENT AUTHORIZATION ──────────────────────────────────────
  const s2Y = d1Y + dH + 4;
  drawSectionHeader(doc, '2. Consent Authorization', s2Y);

  const c1Y = s2Y + 7;
  const cH  = 29;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.roundedRect(12, c1Y, 186, cH, 1.6, 1.6, 'FD');
  doc.setLineWidth(0.3);
  doc.line(102, c1Y + 3, 102, c1Y + cH - 3);

  const authLeftX = 15;
  const authRightX = 106;
  const cr1 = c1Y + 5.5, cr2 = c1Y + 14, cr3 = c1Y + 22.5;
  drawStackedKV(doc, 'Authorized Care Program', consent.program, authLeftX, cr1, 82, 6.8);
  drawStackedKV(doc, 'Consent Template Version', consent.consentVersion, authLeftX, cr2, 82, 6.8);
  drawStackedKV(doc, 'Authorized Person',
    consent.signedBy === 'PATIENT' ? 'Patient (Self)' : `Representative (${consent.relationship || 'N/A'})`,
    authLeftX, cr3, 82, 6.8);

  drawStackedKV(doc, 'Signer Name', consent.signerName, authRightX, cr1, 87, 6.8);
  drawStackedKV(doc, 'Consent Method', (consent.consentMethod || 'SIGNATURE').replace(/_/g, ' '), authRightX, cr2, 87, 6.8);

  // Consent Terms
  const termsY = c1Y + cH + 4;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.4);
  setTeal(doc);
  doc.text('Consent Terms & Conditions:', 12, termsY);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.8);
  setInk(doc);
  const terms = [
    `You agree to participate in the selected service: ${consent.program}.`,
    'These services are voluntary. You may stop them at any time without affecting your clinical care.',
    'Your health information will be protected under HIPAA and used only as allowed by law.',
    'Your health plan may cover these services. A copay or other cost-sharing may apply depending on your policy.',
    'You confirm that you are not receiving the same care management services from another provider or practice.',
    'Your device sends readings to your care team. Use it as directed and take your readings as instructed.'
  ];
  let tY = termsY + 4.5;
  terms.forEach(t => { tY = drawBullet(doc, t, 12, tY, 184); tY += 0.35; });

  // ── SECTION 3: SIGNATURES & CONFIRMATION ──────────────────────────────────
  const s3Y = tY + 8;
  drawSectionHeader(doc, '3. Signatures & Confirmation', s3Y);

  const sigY = s3Y + 8;
  const sigH = 42;
  const sigW = 91;

  // ── Patient signature box ───────────────────────────
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.roundedRect(12, sigY, sigW, sigH, 1.6, 1.6, 'FD');
  // Navy-teal header
  doc.setFillColor(TEAL.r, TEAL.g, TEAL.b);
  doc.roundedRect(12, sigY, sigW, 6.5, 1.6, 1.6, 'F');
  doc.rect(12, sigY + 3.5, sigW, 3, 'F'); // square bottom corners on header
  doc.setFont('helvetica', 'bold'); doc.setFontSize(5.9); doc.setTextColor(255,255,255);
  doc.text('PATIENT OR REPRESENTATIVE SIGNATURE', 15, sigY + 4.6);

  // Signature content
  if (consent.signatureMethod === 'TYPE') {
    doc.setFont('helvetica', 'bolditalic'); doc.setFontSize(11); setInk(doc);
    doc.text(consent.typedSignatureName || consent.signerName, 15, sigY + 20);
    doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
    doc.setLineWidth(0.3);
    doc.line(15, sigY + 24, 98, sigY + 24);
  } else if (consent.patientSignature?.startsWith('data:image')) {
    try { doc.addImage(consent.patientSignature, 'PNG', 15, sigY + 8.5, sigW - 6, 19); } catch { /**/ }
    doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b); doc.setLineWidth(0.3);
    doc.line(15, sigY + 29, 15 + sigW - 8, sigY + 29);
  } else {
    doc.setFont('helvetica', 'bolditalic'); doc.setFontSize(9.5); setSlate6(doc);
    doc.text('[Electronically signed]', 15, sigY + 20);
    doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b); doc.setLineWidth(0.3);
    doc.line(15, sigY + 24, 98, sigY + 24);
  }

  // Signer meta below line
  doc.setFont('helvetica', 'normal'); doc.setFontSize(6.2); setTeal(doc);
  doc.text('Signer:', 15, sigY + 32);
  setInk(doc); doc.setFont('helvetica', 'bold');
  drawFitText(doc, consent.signerName, 28, sigY + 32, 69, 6.2);
  doc.setFont('helvetica', 'normal'); setTeal(doc);
  doc.text('Date:', 15, sigY + 37);
  setInk(doc); doc.setFont('helvetica', 'bold');
  drawFitText(doc, meta.dateTime, 25, sigY + 37, 72, 6.2);

  // ── Nurse signature box ─────────────────────────────
  const nsX = 107;
  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.roundedRect(nsX, sigY, sigW, sigH, 1.6, 1.6, 'FD');
  // Dark navy header
  doc.setFillColor(NAVY.r, NAVY.g, NAVY.b);
  doc.roundedRect(nsX, sigY, sigW, 6.5, 1.6, 1.6, 'F');
  doc.rect(nsX, sigY + 3.5, sigW, 3, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(5.9); doc.setTextColor(255,255,255);
  doc.text('NURSE SIGNATURE', nsX + 3, sigY + 4.6);

  if (consent.nurseSignature?.startsWith('data:image')) {
    try { doc.addImage(consent.nurseSignature, 'PNG', nsX + 3, sigY + 8.5, sigW - 6, 19); } catch { /**/ }
    doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b); doc.setLineWidth(0.3);
    doc.line(nsX + 3, sigY + 29, nsX + sigW - 3, sigY + 29);
  } else {
    doc.setFont('helvetica', 'bolditalic'); doc.setFontSize(9.5); setSlate6(doc);
    doc.text('[Electronically signed]', nsX + 3, sigY + 20);
    doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b); doc.setLineWidth(0.3);
    doc.line(nsX + 3, sigY + 24, nsX + sigW - 3, sigY + 24);
  }

  doc.setFont('helvetica', 'normal'); doc.setFontSize(6.2); setTeal(doc);
  doc.text('Nurse:', nsX + 3, sigY + 32);
  setInk(doc); doc.setFont('helvetica', 'bold');
  drawFitText(doc, consent.nurseName, nsX + 14, sigY + 32, 73, 6.2);
  doc.setFont('helvetica', 'normal'); setTeal(doc);
  doc.text('Date:', nsX + 3, sigY + 37);
  setInk(doc); doc.setFont('helvetica', 'bold');
  drawFitText(doc, meta.dateTime, nsX + 13, sigY + 37, 75, 6.2);

  // ── Audit log box ────────────────────────────────────────────────────────
  const auY = sigY + sigH + 8;
  const auBodyH = 38;

  // Navy header (no circle)
  doc.setFillColor(NAVY.r, NAVY.g, NAVY.b);
  doc.roundedRect(12, auY, 186, 7, 1.6, 1.6, 'F');
  doc.rect(12, auY + 4, 186, 3, 'F');
  doc.setFont('helvetica', 'bold'); doc.setFontSize(6.5); doc.setTextColor(255,255,255);
  doc.text('AUDIT LOG DETAILS', 15, auY + 4.8);

  // Light body
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(SLATE3.r, SLATE3.g, SLATE3.b);
  doc.setLineWidth(0.35);
  doc.roundedRect(12, auY + 7, 186, auBodyH, 1.6, 1.6, 'FD');

  const auditRow1 = auY + 14.5;
  const auditRow2 = auY + 24.5;
  const auditRow3 = auY + 34.5;
  const auCol1 = 15;
  const auCol2 = 68;
  const auCol3 = 119;
  drawStackedKV(doc, 'Consent Document ID', consent.id, auCol1, auditRow1, 47, 5.9, 5.1);
  drawStackedKV(doc, 'Audit Trail Token', consent.auditId, auCol1, auditRow2, 47, 5.9, 5.1);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(5.5); setSlate5(doc);
  doc.text('Decision', auCol1, auditRow3);
  drawBadge(doc, 'GRANTED', auCol1, auditRow3 + 4.7, [5, 150, 105]);

  drawStackedKV(doc, 'Signer', consent.signerName, auCol2, auditRow1, 45, 5.9, 5.1);
  drawStackedKV(doc, 'Captured By', consent.nurseName, auCol2, auditRow2, 45, 5.9, 5.1);
  drawStackedKV(doc, 'Date & Time', consent.signedAt || meta.dateTime, auCol2, auditRow3, 45, 5.9, 5.1);

  drawStackedKV(doc, 'Facility', patient.nursingHome, auCol3, auditRow1, 74, 5.9, 4.8);
  drawStackedKV(doc, 'Capture Device', consent.captureDevice || PRODUCT_NAME, auCol3, auditRow2, 74, 5.9, 5.1);

  drawAllFooters(doc, meta);
  return doc.output('datauristring');
}


export function generateDeviceDeliveryPDF(patient: Patient, device: Device, meta: PDFGeneratorMeta): string {
  const doc = new jsPDF();
  const documentTitle = 'RPM Device Delivery & Activation Confirmation';
  applyPdfMetadata(doc, documentTitle);
  
  drawHeader(doc, documentTitle, patient, meta);

  // Section 1: Device Specs
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('1. HARDWARE SPECIFICATIONS', 15, 100);

  doc.setFillColor(248, 250, 252);
  doc.rect(15, 104, 180, 48, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, 104, 180, 48, 'D');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  
  // Grid display of device specs
  doc.text(`Device Type:`, 20, 111);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.deviceType}`, 65, 111);

  doc.setFont('helvetica', 'normal');
  doc.text(`Brand:`, 20, 117);
  doc.setFont('helvetica', 'bold');
  drawWrappedText(doc, `${device.brand}`, 65, 117, 40, 4);

  doc.setFont('helvetica', 'normal');
  doc.text(`Model:`, 20, 123);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.model}`, 65, 123);

  doc.setFont('helvetica', 'normal');
  doc.text(`Serial Number:`, 110, 111);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.serialNumber}`, 155, 111);

  doc.setFont('helvetica', 'normal');
  doc.text(`Kit ID:`, 110, 117);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.kitId}`, 155, 117);

  doc.setFont('helvetica', 'normal');
  doc.text(`Device ID:`, 110, 123);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.deviceId || 'N/A'}`, 155, 123);

  doc.setFont('helvetica', 'normal');
  doc.text(`Delivery Date:`, 20, 132);
  doc.text(`${device.deliveryDate || meta.dateTime}`, 65, 132);

  doc.text(`Activation Date:`, 110, 132);
  doc.text(`${device.activationDate || 'N/A'}`, 155, 132);

  doc.text(`Delivered By:`, 20, 138);
  doc.text(`${device.deliveredBy}`, 65, 138);

  doc.text(`Activation Status:`, 110, 138);
  doc.setFont('helvetica', 'bold');
  doc.text(`${device.status.replace(/_/g, ' ')}`, 155, 138);

  // Section 2: Clinical Checklist
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2. COMPLIANCE CHECKLIST', 15, 160);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  
  const checklist = [
    { label: 'Device delivered directly to patient:', val: device.deliveredToPatient },
    { label: 'Device correctly assigned in platform:', val: device.assignedToPatient },
    { label: 'Patient received instructions of use:', val: device.instructionsGiven },
    { label: 'Patient or staff demonstrated understanding:', val: device.understandingDemonstrated },
    { label: 'Device successfully activated and transmitting:', val: device.deviceActivated }
  ];

  let checkY = 166;
  checklist.forEach((item) => {
    // draw a tiny checkbox
    doc.setDrawColor(71, 85, 105);
    doc.setFillColor(item.val ? 220 : 255, item.val ? 220 : 255, item.val ? 220 : 255);
    doc.rect(15, checkY - 3, 4, 4, item.val ? 'FD' : 'D');
    if (item.val) {
      doc.setFont('helvetica', 'bold');
      doc.text('X', 16, checkY);
    }
    doc.setFont('helvetica', 'normal');
    doc.text(item.label, 22, checkY);
    checkY += 6.5;
  });

  // Notes section
  checkY += 2;
  doc.setFont('helvetica', 'bold');
  doc.text('Delivery & Activation Notes:', 15, checkY);
  checkY += 5;
  doc.setFillColor(248, 250, 252);
  doc.rect(15, checkY, 180, 15, 'F');
  doc.rect(15, checkY, 180, 15, 'D');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 116, 139);
  drawWrappedText(doc, device.notes || 'No notes recorded.', 18, checkY + 6, 172, 4);
  doc.setTextColor(15, 23, 42);

  // Signatures Section
  checkY += 22;
  doc.setDrawColor(203, 213, 225);
  doc.line(15, checkY, 195, checkY);
  checkY += 6;
  checkY = ensureSectionSpace(doc, 51, checkY, documentTitle, patient, meta);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('3. SIGNATURES & RECIPIENT ACKNOWLEDGEMENT', 15, checkY);
  checkY += 6;

  // Recipient Box
  doc.setFillColor(248, 250, 252);
  doc.rect(15, checkY, 85, 45, 'F');
  doc.rect(15, checkY, 85, 45, 'D');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('RECIPIENT SIGNATURE (PATIENT OR STAFF)', 20, checkY + 5);

  if (device.recipientSignature && device.recipientSignature.startsWith('data:image')) {
    try {
      doc.addImage(device.recipientSignature, 'PNG', 20, checkY + 11, 75, 24);
    } catch (e) {
      console.error('Error adding recipient signature to PDF:', e);
      doc.setFont('helvetica', 'italic');
      doc.text('[Signature Image Error]', 20, checkY + 25);
    }
  } else {
    doc.setFont('helvetica', 'italic');
    doc.text('[Device delivered and verified]', 20, checkY + 25);
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.text(`Patient Representative: ${patient.firstName} ${patient.lastName}`, 20, checkY + 38);
  doc.text(`Date: ${device.deliveryDate || meta.dateTime}`, 20, checkY + 42);

  // Nurse Box
  doc.setFillColor(248, 250, 252);
  doc.rect(110, checkY, 85, 45, 'F');
  doc.rect(110, checkY, 85, 45, 'D');

  doc.setFont('helvetica', 'bold');
  doc.text('NURSE SIGNATURE', 115, checkY + 5);

  if (device.nurseSignature && device.nurseSignature.startsWith('data:image')) {
    try {
      doc.addImage(device.nurseSignature, 'PNG', 115, checkY + 11, 75, 24);
    } catch (e) {
      console.error('Error adding nurse signature to PDF:', e);
      doc.setFont('helvetica', 'italic');
      doc.text('[Signature Image Error]', 115, checkY + 25);
    }
  } else {
    doc.setFont('helvetica', 'italic');
    doc.text('[Electronically signed]', 115, checkY + 25);
  }

  doc.setFont('helvetica', 'normal');
  doc.text(`Nurse: ${device.deliveredBy}`, 115, checkY + 38);
  doc.text(`Date: ${device.deliveryDate || meta.dateTime}`, 115, checkY + 42);

  drawAllFooters(doc, meta);

  return doc.output('datauristring');
}

export function generateMedicalOrderPDF(patient: Patient, order: MedicalOrder, meta: PDFGeneratorMeta): string {
  const doc = new jsPDF();
  const documentTitle = 'Physician Medical Order — RPM Authorization';
  applyPdfMetadata(doc, documentTitle);

  drawHeader(doc, documentTitle, patient, meta);

  // ── Section 1: Order Identity ─────────────────────────────
  let y = 100;
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('1. MEDICAL ORDER DETAILS', 15, y);
  y += 6;

  doc.setFillColor(248, 250, 252);
  doc.rect(15, y, 180, 44, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, y, 180, 44, 'D');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  doc.text(`Order ID:`, 20, y + 7);
  doc.setFont('helvetica', 'bold');
  doc.text(`${order.id}`, 55, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.text(`Version:`, 20, y + 13);
  doc.setFont('helvetica', 'bold');
  doc.text(`${order.orderVersion}`, 55, y + 13);

  doc.setFont('helvetica', 'normal');
  doc.text(`Created:`, 20, y + 19);
  doc.text(`${new Date(order.createdAt).toLocaleString()}`, 55, y + 19);

  doc.text(`Created By:`, 20, y + 25);
  doc.setFont('helvetica', 'bold');
  doc.text(`${order.createdBy}`, 55, y + 25);

  doc.setFont('helvetica', 'normal');
  doc.text(`Assigned Physician:`, 110, y + 7);
  doc.setFont('helvetica', 'bold');
  doc.text(`${order.assignedPhysician}`, 155, y + 7);

  doc.setFont('helvetica', 'normal');
  doc.text(`Program:`, 110, y + 13);
  doc.setFont('helvetica', 'bold');
  doc.text(`${patient.assignedProgram}`, 155, y + 13);

  doc.setFont('helvetica', 'normal');
  doc.text(`Required Device:`, 110, y + 19);
  doc.setFont('helvetica', 'bold');
  doc.text(`${order.deviceType || patient.requiredDevice}`, 155, y + 19);

  doc.setFont('helvetica', 'normal');
  doc.text(`Facility:`, 110, y + 25);
  doc.text(`${patient.nursingHome}`, 155, y + 25);

  // Status stamp
  const statusColor = order.status === 'ORDER_APPROVED' ? [5, 150, 105] : [220, 38, 38];
  const statusLabel = order.status === 'ORDER_APPROVED' ? 'APPROVED' : order.status.replace(/_/g, ' ');
  doc.setFillColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.roundedRect(20, y + 32, 50, 8, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text(statusLabel, 24, y + 37.5);

  y += 50;

  // ── Section 2: Clinical Profile ───────────────────────────
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('2. CLINICAL PROFILE', 15, y);
  y += 6;

  // Conditions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text('Diagnoses / Conditions:', 15, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  if (patient.conditions.length === 0) {
    doc.text('• None listed', 20, y);
    y += 5;
  } else {
    patient.conditions.forEach(c => {
      y = drawWrappedText(doc, `• ${c}`, 20, y, 170, 4.5);
    });
  }
  y += 3;

  // Medications
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text('Current Medications:', 15, y);
  y += 5;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  if (patient.medications.length === 0) {
    doc.text('• None listed', 20, y);
    y += 5;
  } else {
    patient.medications.forEach(m => {
      y = drawWrappedText(doc, `• ${m}`, 20, y, 170, 4.5);
    });
  }
  y += 8;

  // ── Section 3: Physician Approval Block ──────────────────
  y = ensureSectionSpace(doc, 55, y, documentTitle, patient, meta);
  doc.setDrawColor(203, 213, 225);
  doc.line(15, y, 195, y);
  y += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('3. PHYSICIAN APPROVAL', 15, y);
  y += 6;

  // Approval box
  const approvalBoxColor = order.status === 'ORDER_APPROVED' ? [236, 253, 245] : [254, 242, 242];
  const approvalBorderColor = order.status === 'ORDER_APPROVED' ? [167, 243, 208] : [254, 202, 202];
  doc.setFillColor(approvalBoxColor[0], approvalBoxColor[1], approvalBoxColor[2]);
  doc.setDrawColor(approvalBorderColor[0], approvalBorderColor[1], approvalBorderColor[2]);
  doc.roundedRect(15, y, 180, 40, 3, 3, 'FD');

  const isApproved = order.status === 'ORDER_APPROVED';
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(isApproved ? 5 : 185, isApproved ? 150 : 28, isApproved ? 105 : 28);
  doc.text(isApproved ? '✓ ORDER APPROVED' : '✗ ORDER REJECTED / NEEDS REVISION', 22, y + 9);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);

  if (isApproved && order.approvedAt) {
    doc.text(`Approved By: ${order.reviewedBy || 'N/A'}`, 22, y + 17);
    doc.text(`Approval Date: ${new Date(order.approvedAt).toLocaleString()}`, 22, y + 23);
    doc.text(`Physician: ${order.assignedPhysician}`, 22, y + 29);
    doc.text(`Reviewer ID: ${order.reviewedByUserId || 'N/A'}`, 110, y + 17);
    doc.text(`Order Version: ${order.orderVersion}`, 110, y + 23);
  } else if (order.rejectedAt) {
    doc.text(`Reviewed By: ${order.reviewedBy || 'N/A'}`, 22, y + 17);
    doc.text(`Review Date: ${new Date(order.rejectedAt).toLocaleString()}`, 22, y + 23);
    doc.text(`Revision Notes: ${order.revisionNotes || 'None'}`, 22, y + 29);
  } else {
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100, 116, 139);
    doc.text('Pending physician review. Not yet approved.', 22, y + 20);
  }

  y += 48;

  // ── Section 4: Audit Trail ───────────────────────────────
  y = ensureSectionSpace(doc, 30, y, documentTitle, patient, meta);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text('4. AUDIT TRAIL', 15, y);
  y += 6;

  order.auditTrail.forEach((entry, i) => {
    y = ensureSectionSpace(doc, 14, y, documentTitle, patient, meta);
    doc.setFillColor(i % 2 === 0 ? 248 : 241, i % 2 === 0 ? 250 : 245, i % 2 === 0 ? 252 : 249);
    doc.rect(15, y - 3, 180, 12, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(`[${entry.action}]`, 18, y + 3);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(`${new Date(entry.dateTime).toLocaleString()}  •  ${entry.userName}`, 55, y + 3);
    if (entry.notes) {
      y = drawWrappedText(doc, entry.notes, 18, y + 8, 172, 3.5);
    } else {
      y += 10;
    }
  });

  drawAllFooters(doc, meta);
  return doc.output('datauristring');
}
